[package]
name = "hippo-swap"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "4a95654aca6a77fc19d2b6b1cf71c5e79f094acc" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "4a95654aca6a77fc19d2b6b1cf71c5e79f094acc" }
CoinRegistry = { git = "https://github.com/hippospace/aptos-registry.git", subdir = "move", rev = "6873400fd274b2227fc2f5f7a4e2ef5e6ebeeb3c" }

[addresses]
hippo_swap = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"
