[package]
name = "HippoSwap"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "45140fcf79c2afd3ce8c86bb9952e90632533cbb" }
MoveNursery = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/nursery/", rev = "45140fcf79c2afd3ce8c86bb9952e90632533cbb" }
TokenRegistry = { git = "https://github.com/hippospace/aptos-registry.git", subdir = "move", rev = "548fc31d91edac02ccd772b0d6ce22c637ecc7e1" }

[addresses]
Std = "0x1"
AptosFramework = "0x1"
HippoSwap = "0xf70ac33c984f8b7bead655ad239d246f1c0e3ca55fe0b8bfc119aa529c4630e8"
