[package]
name = "hippo-swap"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "a58060f88d66b90a0548a506e22270b04a328db3" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "a58060f88d66b90a0548a506e22270b04a328db3" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "209f9e7016effc7e293794e22d0a7ad860b57bbd" }
[addresses]
hippo_swap = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"
